language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script: 
  - (cd eXperDB-Management-Agent; mvn cobertura:cobertura clean install package)
  - (cd eXperDB-Management-Agent/ant_build; ant -buildfile build.xml deploy)
  
after_success:
  - echo "hello"
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="ffc54244-f7fd-4106-947e-1c9d92e89a9c"

branches:
  only:
    - master
    
before_deploy:
  - mkdir -p deploy
